site_name: Secret Server
site_url: https://workshop.thyintresources.com/secretserver/
dev_addr: '127.0.0.1:8005'
theme:
  name: material
  
  font:
    text: Manrope
    code: Manrope
  
  logo: img/Delinea.svg
  
  favicon: img/favicon.ico
  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  features:
    - search.highlight

plugins:
  - search
  - with-pdf:
      author: Delinea Technical Enablement
      cover_logo: img/secretserver.jpg
      cover_title: Secret Server
      cover_subtitle: Protecting your keys to the kingdom
      copyright: Delinea
      debug_html: false
      enabled_if_env: ENABLE_PDF_EXPORT
extra:
  generator: false

nav:
  - Home: index.md
  - Installing Secret Server: module1/module1.md
  - Basic Configuration: module2/module2.md
  - Users, Groups and Roles: module3/module3.md
  - Folder and Policies: module4/module4.md
  - Secret Templates: module5/module5.md
  - Launchers: module6/module6.md
  - Remote Password Change (RPC): module7/module7.md
  - Secret Workflow: module8/module8.md
  - Discovery: module9/module9.md
  - Auditing and Security: module10/module10.md
  - SSH Jumpbox: module11/module11.md



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences